name: metrics
on: push

jobs:
  runs-on: ubuntu-latest
  node-version:
    steps:
      - name: Log node version
        run: node -V 
      - uses: actions/setup-node@v1
        with:
          node-version: 6
      - name: Log node version
        run: node -V 